src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $started_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $ended_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Task", mappedBy="project_id", orphanRemoval=true)
     */
    private $tasks;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->ended_at;
    }

    public function setEndedAt(?\DateTimeInterface $ended_at): self
    {
        $this->ended_at = $ended_at;

        return $this;
    }

    /**
     * @return Collection|Task[]
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
            $task->setProjectId($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->contains($task)) {
            $this->tasks->removeElement($task);
            // set the owning side to null (unless already changed)
            if ($task->getProjectId() === $this) {
                $task->setProjectId(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Controller/ProjectsController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Entity\Task;
use App\Form\AddProjectType;
use App\Form\AddTaskType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

class ProjectsController extends AbstractController
{
    /**
     * @Route("/manager/projects", name="projects-list")
     */
    public function projectsList(Request $request, SerializerInterface $serializer)
    {
        $projectRepository = $this->getDoctrine()->getRepository(Project::class);
        $projects = $projectRepository->findAll();

        $taskRepository = $this->getDoctrine()->getRepository(Task::class);


        return $this->render('projects/projects-list.html.twig', [
            'controller_name' => 'ManagerController',
            'projects' => $projects
        ]);
    }
    /**
     * @Route("/manager/project/add", name="project-add")
     */
    public function projectAdd(Request $request, SerializerInterface $serializer)
    {
        $project = new Project();

        $projectForm = $this->createForm(AddProjectType::class, $project);
        $projectForm->handleRequest($request);

        if ($projectForm->isSubmitted() && $projectForm->isValid()) {
            $project->setStartedAt(new \DateTime());
            $project->setStatus("Nouveau");

            $this->getDoctrine()->getManager()->persist($project);
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('projects-list');
        }

        return $this->render('projects/project-add.html.twig', [
            'projectForm' => $projectForm->createView()
        ]);
    }
    /**
     * @Route("/manager/project/{id}", name="project-detail")
     */
    public function projectDetail(Request $request, SerializerInterface $serializer, $id)
    {
        $projectRepository = $this->getDoctrine()->getRepository(Project::class);
        $project = $projectRepository->find($id);
        $projects = $projectRepository->findAll();
        $taskRepository = $this->getDoctrine()->getRepository(Task::class);
        $tasks = $taskRepository->findBy(['project_id' => $id]);


        return $this->render('projects/project-detail.html.twig', [
            'controller_name' => 'ManagerController',
            'project' => $project,
            'projects' => $projects,
            'tasks' => $tasks
        ]);
    }
    /**
     * @Route("/manager/project/{id}/task/add", name="task-add")
     */
    public function taskAdd(Request $request, SerializerInterface $serializer, $id)
    {

        $projectRepository = $this->getDoctrine()->getRepository(Project::class);
        $project = $projectRepository->findOneBy(['id' => $id]);

        $task = new Task();
        $taskForm = $this->createForm(AddTaskType::class, $task);
        $taskForm->handleRequest($request);

        if ($taskForm->isSubmitted() && $taskForm->isValid()) {
            $task->setCreatedAt(new \DateTime());
            $task->setProjectId($project);

            $this->getDoctrine()->getManager()->persist($task);
            $this->getDoctrine()->getManager()->flush();
        }

        return $this->render('projects/task-add.html.twig', [
            'taskForm' => $taskForm->createView(),
            'project' => $project
        ]);
    }
}

templates/projects/project-add.html.twig
{% extends 'base.html.twig' %}


{% block body %}
	<h1>
		Ajouter un Projet
	</h1>
	{{ form(projectForm) }}{% endblock %}

templates/projects/project-detail.html.twig
{% extends 'base.html.twig' %}


{% block body %}

	<h1>{{ project.name }}</h1>
	<h5>Créé le
		{{ project.startedAt|date('d/m/Y') }}
	</h5>
	<h5>
		{{ project.tasks|length }}
		Tâche(s) assignée(s) à ce Projet
	</h5>
	<div>

		{# TODO #}
		<form action="" method="post">
			Statut :
			<select name="status">
				{% for project in projects %}
					<option value="{{ project.id }}">
						{{project.status}}
					</option>
				{% endfor %}
			</select>
			<input type="submit" value="Changer">
		</form>


	</div>
	<a href="{{ path('task-add', {id: project.id}) }}">Ajouter une tâche</a>
</a>
<table>
	<thead>
		<tr>
			<th>Nom de la tâche</th>
			<th>Description</th>
			<th>Ajoutée le</th>
		</tr>
	</thead>
	<tbody>
		{% for task in tasks %}
			<tr>
				<td>{{ task.title }}</td>
				<td>{{ task.description }}</td>
				<td>
					{{ task.createdAt|date('d/m/Y') }}
				</td>
			</tr>
		{% endfor %}
	</tbody>
</tbody></table>{% endblock %}

templates/projects/projects-list.html.twig
{% extends 'base.html.twig' %}


{% block body %}
	<a href="{{ path('project-add') }}">Ajouter un projet</a>
	<table>
		<thead>
			<tr>
				<th>Nom du Projet</th>
				<th>Statut</th>
				<th>Tâches</th>
				<th>Ajouté le</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for project in projects %}
				<tr>
					<td>{{ project.name }}</td>
					<td>{{ project.status }}</td>
					<td>
						{{ project.tasks |length }}
					</td>
					<td>
						{{ project.startedAt|date('d/m/Y') }}
					</td>
					<td>
						<a href="{{ path('project-detail', {id: project.id}) }}">Gérer le projet</a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</tbody>
</table>{% endblock %}

templates/projects/task-add.html.twig
{% extends 'base.html.twig' %}


{% block body %}
	<h1>
		Ajouter une tâche au projet
		{{ project.name }}
	</h1>
	{{ form(taskForm) }}{% endblock %}